name: User Story
description: Create a new issue with a user story structure
assignees:
  - bearbearean
body:
  - type: dropdown
    attributes:
      label: As a
      description: Identify who this story is for
      options: [user, admin, developer, "[other]"]
      default: 0
  - type: textarea
    attributes:
      label: I want
      description: Describe what this story is about
      placeholder: "to be able to make pancakes."
  - type: textarea
    attributes:
      label: So that
      description: Motivate why this story is relevant
      placeholder: "I can have a nice breakfast."
