name: User Story
description: Create a new issue with a user story structure
assignees:
  - bearbearean
body:
  - type: dropdown
    attributes:
      label: As a [role]
      description: Identify who this story is for
      options: [user, admin, developer, "[other]"]
      default: 0
  - type: textarea
    attributes:
      label: I want [purpose]
      description: Describe what this story is about
      placeholder: I want to be able to make pancakes.
  - type: textarea
    attributes:
      label: So that [reason]
      description: Motivate why this story is relevant
      placeholder: So that I can have a nice breakfast.
